#!/bin/bash

DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# Find service plist
FILE=$(ls *.plist| head -1) # Returns first .plist file in folder
SERVICE=${FILE%.plist} # Strips .plist
NAME=${SERVICE##*.} # Gets part of service name after last dot

# Unload service
launchctl list | grep $SERVICE > /dev/null \
&& launchctl unload ~/Library/LaunchAgents/com.github.lersveen.backup.plist \
|| echo 'Backup launchd service is not installed'

# Remove plist
rm -f ~/Library/LaunchAgents/com.github.lersveen.backup.plist > /dev/null

# Check that service is not running
launchctl list | grep com.github.lersveen.backup > /dev/null \
&& echo 'Failed to remove backup launchd service' \
|| echo 'Backup launchd service removed successfully'

# Keep terminal open
echo ''
read -p 'Press Enter to exit'